"""Generate .env.example from scan results.

Takes a ScanResult and writes a template file with:
  - one line per variable
  - comment pointing to where it's used in code
  - the default value from code (if any) as the placeholder
"""

from __future__ import annotations

import ast
from pathlib import Path
from typing import List, Optional

from envsleuth.scanner import EnvUsage, ScanResult


HEADER = """\
# Generated by envsleuth — edit this file before committing.
# Each variable below is used somewhere in your code.
# Replace the empty values with real defaults/examples, but don't commit secrets.
"""


def _first_literal_default(usages: List[EnvUsage]) -> Optional[str]:
    """Try to recover a literal default value from one of the usage sites.

    We already know which usages have has_default=True; this re-parses the line
    to pull out the second arg's constant value. It's a bit of a hack but works
    well enough for the common case.
    """
    # TODO: properly thread the default node through from scanner instead of
    # re-reading the file here. Works for now.
    for u in usages:
        if not u.has_default:
            continue
        try:
            source = u.file.read_text(encoding="utf-8")
        except OSError:
            continue
        try:
            tree = ast.parse(source)
        except SyntaxError:
            continue

        for node in ast.walk(tree):
            if not isinstance(node, ast.Call):
                continue
            if node.lineno != u.line:
                continue
            # getenv(name, default) or environ.get(name, default)
            if len(node.args) >= 2:
                default = node.args[1]
                if isinstance(default, ast.Constant):
                    if default.value is None:
                        return ""
                    return str(default.value)
    return None


def build_env_example(scan: ScanResult) -> str:
    """Produce the text content for a .env.example file."""
    lines: List[str] = [HEADER]

    # group usages by name
    grouped: dict = {}
    for u in scan.usages:
        if u.name is None:
            continue
        grouped.setdefault(u.name, []).append(u)

    if not grouped:
        lines.append("# No environment variables found in code.")
        return "\n".join(lines) + "\n"

    for name in sorted(grouped):
        usages = grouped[name]

        # show up to 3 locations
        locations = [f"{u.file}:{u.line}" for u in usages[:3]]
        if len(usages) > 3:
            locations.append(f"...and {len(usages) - 3} more")
        lines.append(f"# used at {', '.join(locations)}")

        default = _first_literal_default(usages)
        if default is not None and default != "":
            lines.append(f"{name}={default}")
        else:
            lines.append(f"{name}=")
        lines.append("")  # blank between groups, easier to scan

    return "\n".join(lines).rstrip() + "\n"


def write_env_example(scan: ScanResult, path: Path, force: bool = False) -> None:
    """Write a .env.example to `path`. Raises FileExistsError if it exists and !force."""
    if path.exists() and not force:
        raise FileExistsError(f"{path} already exists (use --force to overwrite)")
    content = build_env_example(scan)
    path.write_text(content, encoding="utf-8")
