"""Generate .env.example from scan results.

Takes a ScanResult and writes a template file with:
  - one line per variable
  - comment pointing to where it's used in code
  - the default value from code (if any) as the placeholder
"""

from __future__ import annotations

import ast
import os
import re
import secrets
import stat
from pathlib import Path
from typing import List, Optional, Tuple

from envsleuth.scanner import EnvUsage, ScanResult


HEADER = """\
# Generated by envsleuth — edit this file before committing.
# Each variable below is used somewhere in your code.
# Replace the empty values with real defaults/examples, but don't commit secrets.
"""

_PORTABLE_ENV_NAME = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
_SAFE_UNQUOTED = re.compile(r"^[A-Za-z0-9_./,:@%+,-]+$")
_OMITTED_DEFAULT = (
    "# default omitted: it cannot be represented safely for both dotenv and shell"
)


class GenerationError(Exception):
    """Base class for errors that make generation incomplete or unsafe."""


class IncompleteScanError(GenerationError):
    def __init__(self, errors: List[Tuple[Path, str]]) -> None:
        self.errors = list(errors)
        count = len(errors)
        super().__init__(f"scan incomplete: {count} file{'s' if count != 1 else ''} failed")


class InvalidEnvNameError(GenerationError):
    def __init__(self, names: List[str]) -> None:
        self.names = sorted(set(names))
        shown = ", ".join(repr(name) for name in self.names)
        super().__init__(f"cannot generate portable assignments for env name(s): {shown}")


class EnvNameCollisionError(GenerationError):
    def __init__(self, groups: List[List[str]]) -> None:
        self.groups = sorted(
            (sorted(group) for group in groups),
            key=lambda group: tuple(name.casefold() for name in group),
        )
        shown = "; ".join(" / ".join(group) for group in self.groups)
        super().__init__(
            "environment names collide on this platform: " + shown
        )


def _rel(p: Path) -> str:
    """Display paths without leaking a machine-specific absolute prefix."""
    if not p.is_absolute():
        return str(p)
    try:
        return str(p.relative_to(Path.cwd()))
    except ValueError:
        return p.name


def _format_value(raw: str) -> Optional[str]:
    """Return a value with the same result in python-dotenv and POSIX shells."""
    if raw == "":
        return ""
    if raw.endswith("\\"):
        return None
    if any(char not in "\n\t" and not char.isprintable() for char in raw):
        return None
    try:
        raw.encode("utf-8")
    except UnicodeEncodeError:
        return None
    if _SAFE_UNQUOTED.fullmatch(raw):
        return raw
    if "$" not in raw and "`" not in raw:
        escaped = raw.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    if (
        "'" not in raw
        and "${" not in raw
        and "\\\\" not in raw
    ):
        return f"'{raw}'"
    return None


def _literal_from_node(node: Optional[ast.AST]) -> Tuple[Optional[str], bool]:
    """Pull a string default out of an AST node, if it's a literal we recognize."""
    if node is None:
        return None, False
    try:
        value = ast.literal_eval(node)
    except (ValueError, TypeError, SyntaxError, MemoryError, RecursionError):
        return None, True
    if value is None:
        return None, False
    if isinstance(value, (str, bool, int, float)):
        try:
            return str(value), True
        except (ValueError, MemoryError):
            return None, True
    # could also try to handle ast.Name pointing at a module-level constant,
    # but that's a rabbit hole — keeping it simple
    return None, True


def _usage_sort_key(usage: EnvUsage) -> Tuple[str, int, str]:
    return (usage.file.as_posix().casefold(), usage.line, usage.call_type)


def _pick_default(usages: List[EnvUsage]) -> Tuple[Optional[str], bool]:
    """Pick the first portable literal by source location, not scan order."""
    found_unportable = False
    for u in sorted(usages, key=_usage_sort_key):
        if not u.has_default:
            continue
        if u.call_type == "pydantic_settings" and u.default_node is None:
            found_unportable = True
            continue
        val, should_explain = _literal_from_node(u.default_node)
        if val is None:
            found_unportable = found_unportable or should_explain
            continue
        formatted = _format_value(val)
        if formatted is not None:
            return formatted, False
        found_unportable = True
    return None, found_unportable


def _one_line(text: str) -> str:
    pieces: List[str] = []
    for char in text:
        if char == "\r":
            pieces.append("\\r")
        elif char == "\n":
            pieces.append("\\n")
        elif char.isprintable():
            pieces.append(char)
        else:
            pieces.append(ascii(char)[1:-1])
    return "".join(pieces)


def _env_names_case_sensitive() -> bool:
    return os.name != "nt"


def _validate_scan(scan: ScanResult) -> None:
    if scan.errors:
        raise IncompleteScanError(scan.errors)
    invalid = sorted(
        name for name in scan.static_names
        if not _PORTABLE_ENV_NAME.fullmatch(name)
    )
    if invalid:
        raise InvalidEnvNameError(invalid)
    by_folded_name: dict = {}
    case_insensitive_names = set()
    for usage in scan.usages:
        if usage.name is None:
            continue
        by_folded_name.setdefault(
            usage.name.casefold(), set(),
        ).add(usage.name)
        usage_mode = getattr(usage, "case_sensitive", None)
        if usage_mode is False:
            case_insensitive_names.add(usage.name.casefold())

    platform_is_insensitive = not _env_names_case_sensitive()
    collisions = [
        sorted(names)
        for folded, names in by_folded_name.items()
        if len(names) > 1
        and (platform_is_insensitive or folded in case_insensitive_names)
    ]
    if collisions:
        raise EnvNameCollisionError(collisions)


def _append_dynamic_warning(lines: List[str], usages: List[EnvUsage]) -> None:
    if not usages:
        return
    count = len(usages)
    lines.append(
        f"# WARNING: {count} dynamic environment variable "
        f"usage{'s' if count != 1 else ''} could not be resolved."
    )
    lines.append("# Add the runtime names manually; unresolved usages:")
    for usage in sorted(usages, key=_usage_sort_key):
        location = _one_line(f"{_rel(usage.file)}:{usage.line}")
        expression = _one_line(usage.raw_expr or "?")
        lines.append(f"# - {location}: {expression}")
    lines.append("")


def build_env_example(scan: ScanResult) -> str:
    """Produce the text content for a .env.example file."""
    _validate_scan(scan)
    lines: List[str] = [HEADER]

    grouped: dict = {}
    for u in scan.usages:
        if u.name is None:
            continue
        grouped.setdefault(u.name, []).append(u)

    _append_dynamic_warning(lines, scan.dynamic_usages)

    if not grouped:
        if scan.dynamic_usages:
            lines.append("# No statically resolved environment variables found in code.")
        else:
            lines.append("# No environment variables found in code.")
        return "\n".join(lines) + "\n"

    for name in sorted(grouped):
        usages = grouped[name]

        # show up to 3 locations
        usages = sorted(usages, key=_usage_sort_key)
        locations = [
            _one_line(f"{_rel(u.file)}:{u.line}")
            for u in usages[:3]
        ]
        if len(usages) > 3:
            locations.append(f"...and {len(usages) - 3} more")
        lines.append(f"# used at {', '.join(locations)}")

        accepted = sorted({
            candidate
            for usage in usages
            for candidate in getattr(usage, "accepted_names", ())
            if candidate != name
        })
        if accepted:
            shown = ", ".join(_one_line(candidate) for candidate in accepted)
            lines.append(f"# also accepts: {shown}")

        default, default_was_omitted = _pick_default(usages)
        if default_was_omitted:
            lines.append(_OMITTED_DEFAULT)
        lines.append(f"{name}={default or ''}")
        lines.append("")  # blank between groups, easier to scan

    return "\n".join(lines).rstrip() + "\n"


def _stat_fingerprint(info: os.stat_result) -> tuple:
    birthtime_ns = getattr(info, "st_birthtime_ns", None)
    identity_time_ns = (
        birthtime_ns
        if os.name == "nt" and birthtime_ns is not None
        else info.st_ctime_ns
    )
    return (
        info.st_mode,
        info.st_size,
        info.st_mtime_ns,
        identity_time_ns,
        info.st_nlink,
        getattr(info, "st_uid", None),
        getattr(info, "st_gid", None),
    )


def _same_file_snapshot(
    expected: os.stat_result,
    current: os.stat_result,
) -> bool:
    # Device + inode alone is not enough after unlink: Linux can immediately
    # reuse the inode for a different file.
    return (
        os.path.samestat(expected, current)
        and _stat_fingerprint(expected) == _stat_fingerprint(current)
    )


def _unlink_if_same(path: Path, expected: os.stat_result) -> None:
    try:
        current = path.lstat()
    except OSError:
        return
    if not _same_file_snapshot(expected, current):
        return
    try:
        path.unlink()
    except OSError:
        pass


def _write_exclusive(path: Path, content: str) -> bool:
    try:
        stream = path.open("x", encoding="utf-8", newline="\n")
    except FileExistsError:
        return False

    created_stat: Optional[os.stat_result] = None
    try:
        with stream:
            created_stat = os.fstat(stream.fileno())
            try:
                stream.write(content)
                stream.flush()
            finally:
                try:
                    created_stat = os.fstat(stream.fileno())
                except OSError:
                    pass
        try:
            current = path.lstat()
        except OSError as exc:
            raise OSError("output file disappeared during generation") from exc
        if not _same_file_snapshot(created_stat, current):
            raise OSError("output file was replaced during generation")
    except BaseException:
        if created_stat is not None:
            _unlink_if_same(path, created_stat)
        raise
    return True


def write_env_example(scan: ScanResult, path: Path, force: bool = False) -> None:
    """Write a .env.example to `path`. Raises FileExistsError if it exists and !force."""
    content = build_env_example(scan)
    content.encode("utf-8")

    if not force:
        if not _write_exclusive(path, content):
            raise FileExistsError(
                f"{path} already exists (use --force to overwrite)"
            ) from None
        return

    if _write_exclusive(path, content):
        return

    try:
        target_info = path.lstat()
    except FileNotFoundError:
        if _write_exclusive(path, content):
            return
        target_info = path.lstat()

    if stat.S_ISLNK(target_info.st_mode):
        try:
            target_mode = stat.S_IMODE(path.stat().st_mode)
        except FileNotFoundError:
            target_mode = None
    else:
        target_mode = stat.S_IMODE(target_info.st_mode)

    temp_path: Optional[Path] = None
    temp_stat: Optional[os.stat_result] = None
    try:
        for _ in range(10):
            candidate = path.parent / f".envsleuth-{secrets.token_hex(8)}.tmp"
            try:
                stream = candidate.open("x", encoding="utf-8", newline="\n")
            except FileExistsError:
                continue
            temp_path = candidate
            break
        else:
            raise FileExistsError("could not allocate a temporary output file")

        with stream:
            temp_stat = os.fstat(stream.fileno())
            try:
                used_fd_chmod = (
                    target_mode is not None
                    and os.name != "nt"
                    and hasattr(os, "fchmod")
                )
                if used_fd_chmod:
                    os.fchmod(stream.fileno(), target_mode)
                stream.write(content)
                stream.flush()
            finally:
                try:
                    temp_stat = os.fstat(stream.fileno())
                except OSError:
                    pass

        if not _same_file_snapshot(temp_stat, temp_path.lstat()):
            raise OSError("temporary output file was replaced during generation")
        if target_mode is not None and not used_fd_chmod:
            os.chmod(temp_path, target_mode)
            current = temp_path.lstat()
            if not os.path.samestat(temp_stat, current):
                raise OSError("temporary output file was replaced during generation")
            temp_stat = current
        if not _same_file_snapshot(temp_stat, temp_path.lstat()):
            raise OSError("temporary output file was replaced during generation")
        os.replace(temp_path, path)
        temp_path = None
    finally:
        if temp_path is not None and temp_stat is not None:
            _unlink_if_same(temp_path, temp_stat)
