"""Generate .env.example from scan results.

Takes a ScanResult and writes a template file with:
  - one line per variable
  - comment pointing to where it's used in code
  - the default value from code (if any) as the placeholder
"""

from __future__ import annotations

import ast
from pathlib import Path
from typing import List, Optional

from envsleuth.scanner import EnvUsage, ScanResult


HEADER = """\
# Generated by envsleuth — edit this file before committing.
# Each variable below is used somewhere in your code.
# Replace the empty values with real defaults/examples, but don't commit secrets.
"""

# chars that mean "this needs quoting" in .env. # is for comments, $ for var
# expansion in some parsers, the rest are obvious.
_NEEDS_QUOTING = set(' \t#"\'$\\')


def _rel(p: Path) -> str:
    """Display path relative to cwd, fall back to absolute if not possible."""
    try:
        return str(p.relative_to(Path.cwd()))
    except ValueError:
        return str(p)


def _format_value(raw: str) -> str:
    """Format a value for .env. Quote it if it contains anything special.

    python-dotenv is forgiving but bash `source .env` and JS dotenv are not —
    they cut at the first '#' and choke on spaces. Better to over-quote.
    """
    if raw == "":
        return ""
    if any(c in _NEEDS_QUOTING for c in raw):
        # double quotes + escape backslashes and embedded quotes
        escaped = raw.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    return raw


def _literal_from_node(node: Optional[ast.AST]) -> Optional[str]:
    """Pull a string default out of an AST node, if it's a literal we recognize."""
    if node is None:
        return None
    if isinstance(node, ast.Constant):
        if node.value is None:
            return ""  # None default == "no value", same as no default for the example
        return str(node.value)
    # could also try to handle ast.Name pointing at a module-level constant,
    # but that's a rabbit hole — keeping it simple
    return None


def _pick_default(usages: List[EnvUsage]) -> Optional[str]:
    """First usage with a usable literal default wins."""
    for u in usages:
        if not u.has_default:
            continue
        val = _literal_from_node(u.default_node)
        if val is not None:
            return val
    return None


def build_env_example(scan: ScanResult) -> str:
    """Produce the text content for a .env.example file."""
    lines: List[str] = [HEADER]

    grouped: dict = {}
    for u in scan.usages:
        if u.name is None:
            continue
        grouped.setdefault(u.name, []).append(u)

    if not grouped:
        lines.append("# No environment variables found in code.")
        return "\n".join(lines) + "\n"

    for name in sorted(grouped):
        usages = grouped[name]

        # show up to 3 locations
        locations = [f"{_rel(u.file)}:{u.line}" for u in usages[:3]]
        if len(usages) > 3:
            locations.append(f"...and {len(usages) - 3} more")
        lines.append(f"# used at {', '.join(locations)}")

        default = _pick_default(usages)
        if default is not None and default != "":
            lines.append(f"{name}={_format_value(default)}")
        else:
            lines.append(f"{name}=")
        lines.append("")  # blank between groups, easier to scan

    return "\n".join(lines).rstrip() + "\n"


def write_env_example(scan: ScanResult, path: Path, force: bool = False) -> None:
    """Write a .env.example to `path`. Raises FileExistsError if it exists and !force."""
    if path.exists() and not force:
        raise FileExistsError(f"{path} already exists (use --force to overwrite)")
    content = build_env_example(scan)
    path.write_text(content, encoding="utf-8")
